config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "web", to: "pages#web"
  get "projet_web", to: "pages#projet_web"
  get "english", to: "pages#english"
  get '/telecharger-cv', to: 'cvchargers#telecharger_cv', as: 'telecharger_cv'
  get '/cv-interim', to: 'cvchargers#telecharger_cv_interim', as: 'cv_interim'

  get 'test-api', to: 'pages#test'

  resources :contact, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :object, validate: true
  attribute :name, validate: true
  attribute :prenom, validate: true
  attribute :email, validate: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "format d'email invalide"}
  attribute :message, validate: true
  attribute :nickname, captcha: true

  validate :email_not_blacklisted

  BLACKLISTED_EMAILS = ['ericjonesmyemail@gmail.com', 'zekisuquc419@gmail.com', 'xiceruxuk02@gmail.com', "pazapz@mailbox.in.ua", "fiskathr@gmail.com", "cordner.willis@gmail.com", "yawiviseya67@gmail.com", "erica.daily23@gmail.com", "dinanikolskaya99@gmail.com"]

  def email_not_blacklisted
    if BLACKLISTED_EMAILS.include?(email.downcase)
      Rails.logger.warn("[SPAM BLOQUÉ] Email #{email} a tenté d'envoyer un message.")
      errors.add(:email, 'est bloquée pour cause d’abus')
    end
  end

  def headers
    {
      subject: "Message d'Ad.andforward",
      to: 'ad.andforward@gmail.com',
      from: %("#{name}, #{prenom}" <#{email}>)
    }
  end


end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @contact_message = Contact.new
  end

  def create
    # Le CAPTCHA est maintenant géré côté client par Stimulus
    # Pas besoin de vérification côté serveur car le formulaire n'est soumis que si le CAPTCHA est correct

    @contact_message = Contact.new(contact_params)

    if @contact_message.valid?
      ContactMailer.contact_email(@contact_message).deliver_now
      flash[:success] = "Votre message a été envoyé avec succès."
      redirect_to root_path
    else
      flash[:error] = "Votre message n'a malheureusement pas été envoyé. Vérifiez si vous avez bien rempli tous les champs."
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :prenom, :object, :email, :message, :nickname)
  end
end

app/controllers/cvchargers_controller.rb
class CvchargersController < ApplicationController
  def telecharger_cv
    cv_path = Rails.root.join('public', 'CV-Adrien-Francais.pdf')
    send_file cv_path, filename: 'CV-Adrien-Francais_cv.pdf', type: 'application/pdf', disposition: 'inline'
  end

  def telecharger_cv_interim
    cv_path = Rails.root.join('public', 'CV_Adrien.pdf')
    send_file cv_path, filename: 'CV_Adrien_cv.pdf', type: 'application/pdf', disposition: 'inline'
  end
end

app/controllers/pages_controller.rb
require "open-uri"

class PagesController < ApplicationController
  def home
  end

  def web
  end

  def english
  end

  def projet_web
  end

  def test

    today = Date.today.strftime("%Y-%m-%d")
    end_date = (Date.today + 15).strftime("%Y-%m-%d")

    url = "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/paris/#{today}/#{end_date}?unitGroup=us&elements=datetimeEpoch%2Ctemp%2Cfeelslike%2Cconditions%2Cdescription%2Cicon&include=obs%2Cdays&key=#{ENV["WEATHER_KEY"]}&contentType=json"


    begin
      response = JSON.parse(URI.parse(url).read)
      puts JSON.parse(URI.parse(url).read).inspect


      if response["days"].present?
        today = Date.today

        # Filtrer uniquement les jours >= aujourd'hui
        @daily_weather = response["days"]
                          .select { |day| Time.at(day["datetimeEpoch"]).utc.to_date >= today }
                          .map do |day|
          {
            "datetime" => Time.at(day["datetimeEpoch"]).utc.to_date.to_s,
            "temp" => day["temp"],
            "feelslike" => day["feelslike"],
            "description" => day["description"].empty? ? "No description available" : day["description"],
            "icon" => day["icon"]
          }
        end

        puts @daily_weather

      else
        @daily_weather = []
      end

    rescue StandardError => erreur
      Rails.logger.error "Aucune donnée météo trouvée: #{erreur.message}"
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
    render json: @players
  end

  def list
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
    render json: @player
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save!
      flash[:notice] = "Le joueur a été créé avec succès !"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      flash[:notice] = "Le joueur a été modifié avec succès !"
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def player_params
    params.require(:player).permit(:first_name, :last_name, :birth_year, :points_record, :photo, :level, :category)
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/new.html.erb
<div class="main-container">
   <%= render 'pages/navbar', class:"sticky" %>
   <div class="container-form">
      <div class="form-contact mt-6" data-controller="captcha">
        <%= simple_form_for(Contact.new, url: contact_index_path, html: { class: 'custom-form', data: { captcha_target: "form" } }) do |form| %>
          <div class="row">
            <div class="col-md-6">
              <%= form.input :name, label: 'Nom', input_html: { class: 'form-control' } %>
            </div>
            <div class="col-md-6">
              <%= form.input :prenom, label: 'Prénom', input_html: { class: 'form-control' } %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= form.input :email, label: 'Email', input_html: { class: 'form-control' } %>
            </div>
            <div class="col-md-6">
              <%= form.input :object, label: 'Objet', as: :select, collection: ["Cours d'anglais Info", 'Projet Web Info', 'Basketball Info', 'Devis', "Autre"], prompt: 'Sélectionnez un objet', input_html: { class: 'form-control' } %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= form.input :message, label: 'Message', as: :text, input_html: { class: 'form-control', rows: 6 } %>
            </div>
          </div>

          <div class="d-none">
            <%= form.input :nickname, label: false, input_html: { autocomplete: 'off' } %>
          </div>

          <div class="button type--C mt-3">
            <div class="button__line"></div>
            <div class="button__line"></div>
            <span>
              <%= form.button :submit, 'Envoyer', class: 'button__text', data: { action: "captcha#submit" } %>
            </span>
            <div class="button__drow1"></div>
            <div class="button__drow2"></div>
        </div>

        <% end %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AD AND FORWARD</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,300;0,6..12,400;1,6..12,500&family=Open+Sans:ital,wght@0,300;0,400;0,800;1,400;1,600&family=Yatra+One&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% if flash[:success] %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        Votre message a été envoyé avec succès.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>

    <% if flash[:error] %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% end %>
  </body>
</html>

app/views/pages/_footer.html.erb
<footer>
  <div class="footer-copyright text-center">&copy; Developed with ❤️</i> by
    <a href="https://www.adrien-regis.site/" class="white-text" target="_blank">Adrien Régis</a>.
  </div>
</footer>

app/views/pages/_navbar.html.erb
<nav class="navbar-flow ">
  <div class="menu-toggle"><i class="fas fa-bars"></i></div>
  <ul class="menuItems">
    <li class="nav-link"><%= link_to "Home", root_path %></li>
    <li class="nav-link"><%= link_to "About", web_path %></li>
    <li class="nav-link"><%= link_to "English is Facile", english_path %></li>
    <li class="nav-link"><%= link_to "Projet Web", projet_web_path, data: { turbo: false } %></li>
    <li class="nav-link"><%= link_to "Contact",  new_contact_path %></li>
  </ul>
</nav>

<nav class="navbar-flow-b">
  <div class="dropdown">
    <!-- Utilisation d'une icône pour le bouton du dropdown -->
    <button class=" dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="fa-solid fa-bars" style="color: #38acf5;"></i>
    </button>
    <!-- Contenu du dropdown -->
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li class="dropdown-item"><a href="<%= root_path %>">Home</a></li>
      <li class="dropdown-item"><a href="<%= web_path %>">About</a></li>
      <li class="dropdown-item"><a href="<%= english_path %>">English is Facile</a></li>
      <li class="dropdown-item"><a href="<%= projet_web_path %>" data-turbo="false">Projet Web</a></li>
      <li class="dropdown-item"><a href="<%= new_contact_path %>">Contact</a></li>
    </ul>
  </div>
</nav>

app/views/pages/contact.html.erb
<div class="main-container">
   <%= render 'navbar', class:"sticky" %>
  <%= form_with(model: ContactMessage.new, url: new_contact_path) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :message %>
  <%= form.text_area :message %>

  <%= form.submit "Envoyer" %>
<% end %>

</div>

app/views/pages/home.html.erb
<div class="main-container">
   <%= render 'navbar', class:"sticky" %>
  <div class="landing-div">
    <div class="container-landing">
      <div class="welcome">
        <p>Welcome</p>
        <h1>AD.AND FORWARD</h1>
        <h4>Développement Web et Services Linguistiques</h4>
      </div>
      <div class="services-container">
        <div class="card-services">
        <%= link_to projet_web_path, class: "card-link", data: { turbo: false } do %>
          <div class="icon"><i class="fa-solid fa-computer fa-beat fa-lg" style="color: #06befc;"></i></div>
          <div class="service-title"><h2>Développement Web</h2></div>
          <div class="service-description"><p>Projet web complet, ajout de features, maintenance ou encore développement shopify. </p></div>
        <% end %>
        </div>
        <div class="card-services">
         <%= link_to english_path, class: "card-link" do %>
          <div class="icon"><i class="fa-solid fa-book fa-lg" style="color: #06befc;"></i></div>
          <div class="service-title"><h2>English skills</h2></div>
          <div class="service-description"><p>Anglais, outil de communication. Cours de conversation en groupe ou solo. Offres particuliers et entreprises.</p></div>
        <% end %>
        </div>
        <div class="card-services">
         <%= link_to web_path, class: "card-link" do %>
          <div class="icon"><i class="fa-solid fa-info fa-lg" style="color: #06befc;"></i></div>
          <div class="service-title"><h2>About me</h2></div>
          <div class="service-description">Découvrir mon univers en quelques lignes..</div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/projet_web.html.erb
<%= render 'navbar' %>

<section class="hero">
  <div class="background-web">
    <%= link_to new_contact_path, class: "card-link" do %>
      <div class="header">
        <div class="text-js" id="project-text"></div>
      </div>
    <% end %>
  </div>
</section>

<section class="resume">
  <div class="content">
    <%= link_to telecharger_cv_path, target: "_blank" do %>
      <div class="btn-resume">
        <i class="fa fa-download fa-2x" aria-hidden="true"></i>
        <span>Télécharger mon CV<span>
      </div>
    <% end %>
  </div>
</section>

<div class="about-myself">
  <div class="content">
    <div class="hello"></div>
    <div class="quick-presentation mt-3">
      <span class="mesure">Développeur Web freelance</span> depuis deux ans, j'accompagne mes clients dans la conception et le développement de solutions numériques adaptées à leurs besoins.
      Issu d'une <span class="mesure">reconversion professionnelle</span>, j'ai su transformer ma passion en expertise, alliant rigueur et créativité dans chaque projet.
      En parallèle, j'interviens en tant que <span class="mesure">professeur assistant</span> en programmation orientée objet au Wagon et poursuis un perfectionnement continu à <span class="mesure">l'école 42</span> afin d'affiner mes compétences et rester à la pointe des technologies.
      Vous trouverez ici un <span class="mesure">échantillon</span> de mes réalisations.
    </div>
  </div>
</div>

<section class="projects">

  <div class="project d-flex flex-column flex-md-row align-items-center">
    <%= image_tag("courtside.png", class: "project-image") %>
    <div class="project-info d-flex flex-column justify-content-between text-center text-md-start mt-3 mt-md-0">
      <h3>CourtSideClub</h3>
      <p>Plateforme révolutionnaire qui place les supporters au cœur de l'action en leur donnant un véritable pouvoir de décision sur la gestion d'une équipe de basket 3X3 professionnelle. Gamification complète avec système de niveaux et votes démocratiques.</p>
      <p class="stack-tech"><strong>Technologies utilisées :</strong></p>
      <ul class="stack-list text-start">
        <li><strong>Backend :</strong> Ruby on Rails 7.1.5 🛠️</li>
        <li><strong>Frontend :</strong> Bootstrap 5.3, SCSS/Sass, Font Awesome 6.1 🎨</li>
        <li><strong>Framework JS :</strong> Hotwire (Turbo + Stimulus), Importmap Rails ⚡</li>
        <li><strong>Base de données :</strong> PostgreSQL 🗂️</li>
        <li><strong>Authentification :</strong> Devise avec autorisation Pundit 🔑</li>
        <li><strong>Stockage :</strong> Active Storage + Cloudinary pour les images ☁️</li>
        <li><strong>Fonctionnalités :</strong> Système de gamification, quiz interactifs, votes démocratiques 🎮</li>
        <li><strong>Internationalisation :</strong> Support multilingue (FR/EN) 🌍</li>
      </ul>
       <div class="button type--C">
        <a href="https://www.courtsideclub.io" target="_blank" class="text-decoration-none text-dark">
          <div class="button__line"></div>
          <div class="button__line"></div>
          <span class="button__text">Voir le site</span>
          <div class="button__drow1"></div>
          <div class="button__drow2"></div>
        </a>
      </div>
    </div>
  </div>

  <div class="project d-flex flex-column flex-md-row align-items-center">
    <%= image_tag("tournamentgo.png", class: "project-image") %>
    <div class="project-info d-flex flex-column justify-content-between text-center text-md-start mt-3 mt-md-0">
      <h3>Tournament Go</h3>
      <p>Application de gestion de tournois de basket-ball développée pour répondre aux besoins d'organisation rapide et efficace. Gestion complète des équipes, poules, classements automatiques et planning des arbitres.</p>
      <p class="stack-tech"><strong>Technologies utilisées :</strong></p>
      <ul class="stack-list text-start">
        <li><strong>Backend :</strong> Ruby on Rails 7.1.5 🛠️</li>
        <li><strong>Frontend :</strong> Bootstrap 5, Font Awesome, SCSS 🎨</li>
        <li><strong>Base de données :</strong> PostgreSQL 🗂️</li>
        <li><strong>Authentification :</strong> Devise 🔑</li>
        <li><strong>Stockage :</strong> Cloudinary pour les images ☁️</li>
        <li><strong>Déploiement :</strong> Heroku 🌐</li>
        <li><strong>Fonctionnalités :</strong> Gestion des tournois, classements automatiques, planning arbitres 🏆</li>
        <li><strong>Développement :</strong> IA assistée pour l'accélération frontend 🤖</li>
      </ul>
       <div class="button type--C">
        <a href="https://www.tournamentgo.live" target="_blank" class="text-decoration-none text-dark">
          <div class="button__line"></div>
          <div class="button__line"></div>
          <span class="button__text">Voir le site</span>
          <div class="button__drow1"></div>
          <div class="button__drow2"></div>
        </a>
      </div>
    </div>
  </div>

  <div class="project d-flex flex-column flex-md-row align-items-center">
    <%= image_tag("basketball_finder.png", class: "project-image") %>
    <div class="project-info d-flex flex-column justify-content-between text-center text-md-start mt-3 mt-md-0">
      <h3>Basketball Finder</h3>
      <p>Une application jeu visant à renforcer l'engagement des fans grâce à la gamification et une interaction en temps réel avec leur club favori.</p>
      <p class="stack-tech"><strong>Technologies utilisées :</strong></p>
      <ul class="stack-list text-start">
        <li><strong>Backend :</strong> Ruby on Rails 🛠️</li>
        <li><strong>Frontend :</strong> Stimulus.js, JavaScript, Bootstrap, CSS 🎨</li>
        <li><strong>Gestion des inputs :</strong> Algorithme Jaro-Winkler pour la reconnaissance des noms des joueurs 🔍</li>
        <li><strong>Base de données :</strong> PostgreSQL 🗂️</li>
        <li><strong>Déploiement :</strong> Heroku 🌐</li>
        <li><strong>Authentification :</strong> Devise pour la gestion des utilisateurs 🔑</li>
      </ul>
       <div class="button type--C">
        <a href="https://www.findtheplayer.quest" target="_blank" class="text-decoration-none text-dark">
          <div class="button__line"></div>
          <div class="button__line"></div>
          <span class="button__text">Voir le site</span>
          <div class="button__drow1"></div>
          <div class="button__drow2"></div>
        </a>
      </div>
    </div>
  </div>

  <div class="project d-flex flex-column flex-md-row align-items-center">
    <%= image_tag("portfolio.png", class: "project-image") %>
    <div class="project-info d-flex flex-column justify-content-between text-center text-md-start mt-3 mt-md-0">
      <h3>Mon Portfolio</h3>
      <p>Site personnel permettant de présenter mes projets, compétences et mon parcours en tant que développeur.</p>
      <p class="stack-tech"><strong>Technologies utilisées :</strong></p>
      <ul class="stack-list text-start">
        <li><strong>Backend :</strong> Ruby on Rails 🛠️</li>
        <li><strong>Frontend :</strong> HTML, CSS, Bootstrap 🎨</li>
        <li><strong>Gestion des emails :</strong> Protocole SMTP pour l'envoi sécurisé 📩</li>
        <li><strong>Base de données :</strong> PostgreSQL 🗂️</li>
        <li><strong>Déploiement :</strong> Heroku 🌐</li>
      </ul>
      <div class="button type--C">
        <a href="https://www.adrien-regis.site" target="_blank" class="text-decoration-none text-dark">
          <div class="button__line"></div>
          <div class="button__line"></div>
          <span class="button__text">Voir le site</span>
          <div class="button__drow1"></div>
          <div class="button__drow2"></div>
        </a>
      </div>
    </div>
  </div>

  <div class="project d-flex flex-column flex-md-row align-items-center">
    <%= image_tag("pepites.png", class: "project-image") %>
    <div class="project-info d-flex flex-column justify-content-between text-center text-md-start mt-3 mt-md-0">
      <h3>Les Pépites d'Elo</h3>
      <p>Digitalisation d'une boutique physique située sur Amiens, optimisant la présence en ligne pour maximiser les ventes et toucher une clientèle plus large.</p>
      <p class="stack-tech"><strong>Technologies utilisées :</strong></p>
      <ul class="stack-list text-start">
        <li><strong>Backend :</strong> Shopify & Liquid 🛍️</li>
        <li><strong>Frontend :</strong> Embedded CSS, JavaScript 🎨</li>
        <li><strong>Gestion du catalogue :</strong> Outils Shopify pour la gestion des stocks et des produits 📦</li>
        <li><strong>Paiement & commandes :</strong> Intégration des solutions Shopify Payments & gestion des paniers 🛒</li>
        <li><strong>SEO & marketing :</strong> Optimisation des balises meta, outils d'automatisation marketing Shopify 📈</li>
        <li><strong>Déploiement & hébergement :</strong> Infrastructure Shopify sécurisée 🔒</li>
      </ul>
      <div class="button type--C">
        <a href="https://lespepitesdelo.com/" target="_blank" class="text-decoration-none text-dark">
          <div class="button__line"></div>
          <div class="button__line"></div>
          <span class="button__text">Voir le site</span>
          <div class="button__drow1"></div>
          <div class="button__drow2"></div>
        </a>
      </div>
    </div>
  </div>

  <div class="project d-flex flex-column flex-md-row align-items-center">
    <%= image_tag("osteopathie.png", class: "project-image") %>
    <div class="project-info d-flex flex-column justify-content-between text-center text-md-start mt-3 mt-md-0">
      <h3>Site d'Ostéopathie</h3>
      <p>Un site vitrine conçu pour améliorer la visibilité en ligne d'un cabinet d'ostéopathie, en mettant en avant les services, les spécialités et la prise de rendez-vous en ligne.</p>
      <p class="stack-tech"><strong>Technologies utilisées :</strong></p>
      <ul class="stack-list text-start">
        <li><strong>Plateforme :</strong> Webflow 🌐</li>
        <li><strong>Frontend :</strong> HTML, CSS, JavaScript 🎨</li>
        <li><strong>Gestion des animations :</strong> Interactions Webflow ⚡</li>
        <li><strong>SEO :</strong> Optimisation des balises meta et structure de contenu 📈</li>
        <li><strong>Formulaires :</strong> Webflow Forms avec intégration email 📩</li>
        <li><strong>Hébergement :</strong> Webflow Hosting sécurisé 🔒</li>
      </ul>
    </div>
  </div>
</section>

app/views/pages/test.html.erb
<%= @daily_weather %>

app/views/pages/web.html.erb
<div class="main-container">
  <%= render 'navbar', class:"sticky" %>
  <div class="about-me-container">
    <div class="left-div">
      <h1 >About me</h1>
      <div class="photo-prez">
        <%= image_tag("adrien.jpg", width: 250, class: "photo-home") %>
      </div>
      <div class="button type--C">
        <%= link_to projet_web_path, class:"card-link", data: { turbo: false } do %>
        <div class="button__line"></div>
        <div class="button__line"></div>
        <span class="button__text">Mes projets</span>
        <div class="button__drow1"></div>
        <div class="button__drow2"></div>
        <% end %>
      </div>
    </div>
    <div class="right-div">
      <div class="col" ontouchstart="this.classList.toggle('hover');">
				<div class="container-card">
					<div class="front" style="background-image: url('<%= asset_path('basketball.jpg') %>')">
						<div class="inner">
							<p>Basketball</p>
              <span>Joueur et Entraineur</span>
						</div>
					</div>
					<div class="back">
						<div class="inner">
						  <p> Entraîneur et joueur passionné depuis plus de 15 ans, le basket est mon premier amour. Chaque dribble, chaque panier raconte une histoire de détermination et d'esprit d'équipe. C'est dans le monde du basket que j'ai forgé mon caractère et appris à travailler en équipe.  </p>
						</div>
					</div>
				</div>
			</div>

      <div class="col" ontouchstart="this.classList.toggle('hover');">
				<div class="container-card">
					<div class="front" style="background-image: url('<%= asset_path('coding.jpg') %>')">
						<div class="inner">
							<p>Code</p>
              <span>Programmation / les internets</span>
						</div>
					</div>
					<div class="back">
						<div class="inner">
						  <p>Des bancs du lycée à la ligne de code, ma reconversion dans le développement web est un nouveau chapitre passionnant. Transformant des idées en lignes de code, je construis des expériences en ligne engageantes et innovantes.</p>
						</div>
					</div>
				</div>
			</div>

      <div class="col" ontouchstart="this.classList.toggle('hover');">
				<div class="container-card">
					<div class="front" style="background-image: url('<%= asset_path('reading.jpg') %>')">
						<div class="inner">
							<p>Lecture</p>
              <span>Littérature and Co.</span>
						</div>
					</div>
					<div class="back">
						<div class="inner">
						  <p>Ex-enseignant de littérature, je trouve dans les fictions policières et d'anticipation non seulement une échappatoire, mais aussi un reflet poignant de la vie. Chaque livre offre un regard unique sur notre réalité. Go read Paul Auster, "The Brooklyn Follies"</p>
						</div>
					</div>
				</div>
			</div>

      <div class="col" ontouchstart="this.classList.toggle('hover');">
				<div class="container-card">
					<div class="front" style="background-image: url('<%= asset_path('guitar.jpg') %>')">
						<div class="inner">
							<p>Musique</p>
              <span>Overdosing Spotify</span>
						</div>
					</div>
					<div class="back">
						<div class="inner">
						  <p>La musique est une autre passion qui résonne en moi. Ma collection d'instruments est une symphonie de souvenirs et d'inspirations des pays que j'ai pû visiter, toujours prête à donner vie à de nouvelles mélodies.</p>
						</div>
					</div>
				</div>
			</div>

      <div class="col" ontouchstart="this.classList.toggle('hover');">
				<div class="container-card">
					<div class="front" style="background-image: url('<%= asset_path('teaching.jpg') %>')">
						<div class="inner">
							<p>Enseignement</p>
              <span>Apprendre, partager, transmettre</span>
						</div>
					</div>
					<div class="back">
						<div class="inner">
						  <p>L'enseignement est un fil conducteur dans ma vie. Du terrain de basket à la salle de classe, j'ai enseigné le basket, l'anglais et la littérature. Actuellement, je partage ma passion pour l'enseignement dans une école de programmation.</p>
						</div>
					</div>
				</div>
			</div>

      <div class="col" ontouchstart="this.classList.toggle('hover');">
				<div class="container-card">
					<div class="front" style="background-image: url('<%= asset_path('english.jpg') %>')">
						<div class="inner">
							<p>Anglais</p>
              <span>Langue et Culture</span>
						</div>
					</div>
					<div class="back">
						<div class="inner">
						  <p>Amoureux des langues et globe-trotter, je pense l'anglais comme un pont vers des mondes divers, favorisant la compréhension et la connexion humaine. Chaque mot tisse des liens, chaque conversation dévoile des mondes.</p>
						</div>
					</div>
				</div>
			</div>

    </div>
  </div>

 
</div>